# Generated by Django 3.0.5 on 2020-06-06 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='имя')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='цена')),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
