# Generated by Django 3.0.5 on 2020-06-06 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='price',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='age'),
            preserve_default=False,
        ),
    ]
